## 파일명 : batter_preprocessing_correlation.ipynb
- 2010~2019 타자 데이터 전처리
- 2010~2019 MLB 시즌 랭킹 데이터 전처리 
- 타자 지표와 PCT 상관계수 구함 

In [0]:
# 타자 데이터 전처리

import pandas as pd
import numpy as np 

In [0]:
bat_10 = pd.read_csv('../Data/MLB_data_edit/2010_bat.csv')
bat_10.head()

Unnamed: 0         Player Team Pos    G   AB    R   TH    H  2B  ...  CS  \
0           0  Ichiro Suzuki  SEA  OF  162  680   74  214  175  30  ...   9   
1           1    Derek Jeter  NYY  SS  157  663  111  179  136  30  ...   5   
2           2  Michael Young  TEX  3B  157  656   99  186  126  36  ...   2   
3           3    Juan Pierre  CWS  OF  160  651   96  179  157  18  ...  18   
4           4   Rickie Weeks  MIL  DH  160  651  112  175  110  32  ...   4   

   BB   SO  SH  SF  HBP    AVG    OBP    SLG    OPS  
0  45   86   3   1    3  0.315  0.359  0.394  0.753  
1  63  106   1   3    9  0.270  0.340  0.370  0.710  
2  50  115   0  11    1  0.284  0.330  0.444  0.774  
3  45   47  15   2   21  0.275  0.341  0.316  0.657  
4  76  184   0   2   25  0.269  0.366  0.464  0.830  

[5 rows x 24 columns]

In [0]:
bat_11 = pd.read_csv('../Data/MLB_data_edit/2011_bat.csv')

In [0]:
bat_12 = pd.read_csv('../Data/MLB_data_edit/2012_bat.csv')

In [0]:
bat_13 = pd.read_csv('../Data/MLB_data_edit/2013_bat.csv')

In [0]:
bat_14 = pd.read_csv('../Data/MLB_data_edit/2014_bat.csv')

In [0]:
bat_15 = pd.read_csv('../Data/MLB_data_edit/2015_bat.csv')

In [0]:
bat_16 = pd.read_csv('../Data/MLB_data_edit/2016_bat.csv')

In [0]:
bat_17 = pd.read_csv('../Data/MLB_data_edit/2017_bat.csv')

In [0]:
bat_18 = pd.read_csv('../Data/MLB_data_edit/2018_bat.csv')

In [0]:
bat_19 = pd.read_csv('../Data/MLB_data_edit/2019_bat.csv')

In [0]:
rank_10 = pd.read_csv('../Data/MLB_Season_Ranking/2010_ranking.csv')

In [0]:
rank_11 = pd.read_csv('../Data/MLB_Season_Ranking/2011_ranking.csv')

In [0]:
rank_12 = pd.read_csv('../Data/MLB_Season_Ranking/2012_ranking.csv')

In [0]:
rank_13 = pd.read_csv('../Data/MLB_Season_Ranking/2013_ranking.csv')

In [0]:
rank_14 = pd.read_csv('../Data/MLB_Season_Ranking/2014_ranking.csv')

In [0]:
rank_15 = pd.read_csv('../Data/MLB_Season_Ranking/2015_ranking.csv')

In [0]:
rank_16 = pd.read_csv('../Data/MLB_Season_Ranking/2016_ranking.csv', encoding = 'euc-kr')

In [0]:
rank_17 = pd.read_csv('../Data/MLB_Season_Ranking/2017_ranking.csv', encoding = 'euc-kr')

In [0]:
rank_18 = pd.read_csv('../Data/MLB_Season_Ranking/2018_ranking.csv', encoding = 'euc-kr')

In [0]:
rank_19 = pd.read_csv('../Data/MLB_Season_Ranking/2019_ranking.csv', encoding = 'euc-kr')

In [0]:
bat_10['Year'] = 2010

In [0]:
bat_11['Year'] = 2011

In [0]:
bat_12['Year'] = 2012

In [0]:
bat_13['Year'] = 2013

In [0]:
bat_14['Year'] = 2014

In [0]:
bat_15['Year'] = 2015

In [0]:
bat_16['Year'] = 2016

In [0]:
bat_17['Year'] = 2017

In [0]:
bat_18['Year'] = 2018

In [0]:
bat_19['Year'] = 2019

In [0]:
rank_10['Year'] = 2010

In [0]:
rank_11['Year'] = 2011

In [0]:
rank_12['Year'] = 2012

In [0]:
rank_13['Year'] = 2013

In [0]:
rank_14['Year'] = 2014

In [0]:
rank_15['Year'] = 2015

In [0]:
rank_16['Year'] = 2016

In [0]:
rank_17['Year'] = 2017

In [0]:
rank_18['Year'] = 2018

In [0]:
rank_19['Year'] = 2019

In [0]:
bat_total = pd.concat([bat_10,bat_11,bat_12,bat_13,bat_14,bat_15,bat_16,bat_17,bat_18,bat_19])

In [0]:
rank_total = pd.concat([rank_10,rank_11,rank_12,rank_13,rank_14,rank_15,rank_16,rank_17,rank_18,rank_19])

In [0]:
del bat_total['Unnamed: 0']

In [0]:
bat_total

Player Team Pos    G   AB    R   TH    H  2B  3B  ...  BB   SO  \
0       Ichiro Suzuki  SEA  OF  162  680   74  214  175  30   3  ...  45   86   
1         Derek Jeter  NYY  SS  157  663  111  179  136  30   3  ...  63  106   
2       Michael Young  TEX  3B  157  656   99  186  126  36   3  ...  50  115   
3         Juan Pierre  CWS  OF  160  651   96  179  157  18   3  ...  45   47   
4        Rickie Weeks  MIL  DH  160  651  112  175  110  32   4  ...  76  184   
..                ...  ...  ..  ...  ...  ...  ...  ...  ..  ..  ...  ..  ...   
688       Jose Rondon  BAL  2B    1    1    0    0    0   0   0  ...   0    0   
689   Travis d'Arnaud  LAD   C    1    1    0    0    0   0   0  ...   0    0   
690     Aaron Altherr   SF  OF    1    1    0    0    0   0   0  ...   0    1   
691       Rob Brantly  PHI   C    1    1    0    0    0   0   0  ...   0    1   
692  John Ryan Murphy  ATL   C    1    1    0    0    0   0   0  ...   0    0   

     SH  SF  HBP    AVG    OBP    SLG    OPS  Year  
0     3   1    3  0.315  0.359  0.394  0.753  2010  
1     1   3    9  0.270  0.340  0.370  0.710  2010  
2     0  11    1  0.284  0.330  0.444  0.774  2010  
3    15   2   21  0.275  0.341  0.316  0.657  2010  
4     0   2   25  0.269  0.366  0.464  0.830  2010  
..   ..  ..  ...    ...    ...    ...    ...   ...  
688   0   0    0  0.000  0.000  0.000  0.000  2019  
689   0   0    0  0.000  0.000  0.000  0.000  2019  
690   0   0    0  0.000  0.000  0.000  0.000  2019  
691   0   0    0  0.000  0.000  0.000  0.000  2019  
692   0   0    0  0.000  0.000  0.000  0.000  2019  

[6848 rows x 24 columns]

In [0]:
rank_total.sample(5)

Team    W   L    PCT  GB   HOME   AWAY   RS   RA  DIFF  Year
3   MIN  101  61  0.623   6  46-35  55-26  939  754   185  2019
19  PIT   75  87  0.463  29  44-37  31-50  668  731   -63  2017
19  CHW   76  86  0.469  24  40-41  36-45  622  701   -79  2015
11   SF   86  76  0.531  16  46-35  40-41  570  578    -8  2011
25  DET   64  98  0.395  44  38-43  26-55  630  796  -166  2018

In [0]:
print(bat_total)

               Player Team Pos    G   AB    R   TH    H  2B  3B  ...  BB   SO  \
0       Ichiro Suzuki  SEA  OF  162  680   74  214  175  30   3  ...  45   86   
1         Derek Jeter  NYY  SS  157  663  111  179  136  30   3  ...  63  106   
2       Michael Young  TEX  3B  157  656   99  186  126  36   3  ...  50  115   
3         Juan Pierre  CWS  OF  160  651   96  179  157  18   3  ...  45   47   
4        Rickie Weeks  MIL  DH  160  651  112  175  110  32   4  ...  76  184   
..                ...  ...  ..  ...  ...  ...  ...  ...  ..  ..  ...  ..  ...   
688       Jose Rondon  BAL  2B    1    1    0    0    0   0   0  ...   0    0   
689   Travis d'Arnaud  LAD   C    1    1    0    0    0   0   0  ...   0    0   
690     Aaron Altherr   SF  OF    1    1    0    0    0   0   0  ...   0    1   
691       Rob Brantly  PHI   C    1    1    0    0    0   0   0  ...   0    1   
692  John Ryan Murphy  ATL   C    1    1    0    0    0   0   0  ...   0    0   

     SH  SF  HBP    AVG    

In [0]:
bat_total.isnull().sum()

Player    0
Team      0
Pos       0
G         0
AB        0
R         0
TH        0
H         0
2B        0
3B        0
HR        0
RBI       0
SB        0
CS        0
BB        0
SO        0
SH        0
SF        0
HBP       0
AVG       0
OBP       0
SLG       0
OPS       0
Year      0
dtype: int64

In [0]:
# 상관계수 구하기 위한 변수 만들기 for batter (독립변수)
import numpy as np
# 상관계수 :  0.1 이하 : 무시
# ~0.3 이하 :  약한 상관관계
# ~0.7 이하 :  뚜렷한 상관관계
# np.corrcoef() : 상관계수 계산함수
# 대각선을 기준으로 대칭인 행렬
# 대각선을 제외하고 값을 확인하면 된다
# 0.22536935 => 약한 상관관계
bat_indexR=bat_total.groupby(by=['Year','Team']).R.mean() 
bat_indexTH=bat_total.groupby(by=['Year','Team']).TH.mean()
bat_indexH=bat_total.groupby(by=['Year','Team']).H.mean()
bat_index2B=bat_total.groupby(by=['Year','Team'])['2B'].mean()
bat_index3B=bat_total.groupby(by=['Year','Team'])['3B'].mean()
bat_indexHR=bat_total.groupby(by=['Year','Team']).HR.mean()
bat_indexRBI=bat_total.groupby(by=['Year','Team']).RBI.mean()
bat_indexSB=bat_total.groupby(by=['Year','Team']).SB.mean()
bat_indexCS=bat_total.groupby(by=['Year','Team']).CS.mean()
bat_indexBB=bat_total.groupby(by=['Year','Team']).BB.mean()
bat_indexSO=bat_total.groupby(by=['Year','Team']).SO.mean()
bat_indexSH=bat_total.groupby(by=['Year','Team']).SH.mean()
bat_indexSF=bat_total.groupby(by=['Year','Team']).SF.mean()
bat_indexHBP=bat_total.groupby(by=['Year','Team']).HBP.mean()
bat_indexAVG=bat_total.groupby(by=['Year','Team']).AVG.mean()
bat_indexOBP=bat_total.groupby(by=['Year','Team']).OBP.mean()
bat_indexSLG=bat_total.groupby(by=['Year','Team']).SLG.mean()
bat_indexOPS=bat_total.groupby(by=['Year','Team']).OPS.mean()


In [0]:
# 상관계수 구하기 위한 변수 만들기 for 승률(종속변수)
rank_total_k = rank_total.sort_values(by=['Year','Team']) 

In [0]:
#상관계수 구하기 
np.corrcoef(bat_indexR,rank_total_k['PCT'])

array([[1.        , 0.46582901],
       [0.46582901, 1.        ]])

In [0]:
#상관계수 구하기 
np.corrcoef(bat_indexTH,rank_total_k['PCT'])

array([[1.       , 0.2883857],
       [0.2883857, 1.       ]])

In [0]:
#상관계수 구하기 
np.corrcoef(bat_indexH,rank_total_k['PCT'])

array([[1.        , 0.17704569],
       [0.17704569, 1.        ]])

In [0]:
#상관계수 구하기 
np.corrcoef(bat_index2B,rank_total_k['PCT'])

array([[1.        , 0.31835109],
       [0.31835109, 1.        ]])

In [0]:
#상관계수 구하기 
np.corrcoef(bat_index3B,rank_total_k['PCT'])

array([[1.        , 0.02751998],
       [0.02751998, 1.        ]])

In [0]:
#상관계수 구하기 
np.corrcoef(bat_indexHR,rank_total_k['PCT'])

array([[1.        , 0.36342579],
       [0.36342579, 1.        ]])

In [0]:
#상관계수 구하기 
np.corrcoef(bat_indexRBI,rank_total_k['PCT'])

array([[1.        , 0.46609286],
       [0.46609286, 1.        ]])

In [0]:
#상관계수 구하기 
np.corrcoef(bat_indexSB,rank_total_k['PCT'])

array([[1.        , 0.01152051],
       [0.01152051, 1.        ]])

In [0]:
#상관계수 구하기 
np.corrcoef(bat_indexCS,rank_total_k['PCT'])

array([[ 1.        , -0.06969977],
       [-0.06969977,  1.        ]])

In [0]:
#상관계수 구하기 
np.corrcoef(bat_indexBB,rank_total_k['PCT'])

array([[1.        , 0.38522231],
       [0.38522231, 1.        ]])

In [0]:
#상관계수 구하기 
np.corrcoef(bat_indexSO,rank_total_k['PCT'])

array([[ 1.        , -0.01383354],
       [-0.01383354,  1.        ]])

In [0]:
#상관계수 구하기 
np.corrcoef(bat_indexSH,rank_total_k['PCT'])

array([[ 1.        , -0.05826497],
       [-0.05826497,  1.        ]])

In [0]:
#상관계수 구하기 
np.corrcoef(bat_indexSF,rank_total_k['PCT'])

array([[1.       , 0.2872214],
       [0.2872214, 1.       ]])

In [0]:
#상관계수 구하기 
np.corrcoef(bat_indexHBP,rank_total_k['PCT'])

array([[1.        , 0.22498279],
       [0.22498279, 1.        ]])

In [0]:
#상관계수 구하기 
np.corrcoef(bat_indexAVG,rank_total_k['PCT'])

array([[1.        , 0.19411922],
       [0.19411922, 1.        ]])

In [0]:
#상관계수 구하기 
np.corrcoef(bat_indexOBP,rank_total_k['PCT'])

array([[1.        , 0.27472181],
       [0.27472181, 1.        ]])

In [0]:
#상관계수 구하기 
np.corrcoef(bat_indexSLG,rank_total_k['PCT'])

array([[1.        , 0.30031062],
       [0.30031062, 1.        ]])

In [0]:
#상관계수 구하기 
np.corrcoef(bat_indexOPS,rank_total_k['PCT'])

array([[1.        , 0.31315581],
       [0.31315581, 1.        ]])

In [0]:
np.corrcoef(bat_indexR,rank_total_k['PCT'])
np.corrcoef(bat_indexTH,rank_total_k['PCT'])
np.corrcoef(bat_indexH,rank_total_k['PCT'])
np.corrcoef(bat_index2B,rank_total_k['PCT'])
np.corrcoef(bat_index3B,rank_total_k['PCT'])
np.corrcoef(bat_indexHR,rank_total_k['PCT'])
np.corrcoef(bat_indexRBI,rank_total_k['PCT'])
np.corrcoef(bat_indexSB,rank_total_k['PCT'])
np.corrcoef(bat_indexCS,rank_total_k['PCT'])
np.corrcoef(bat_indexBB,rank_total_k['PCT'])
np.corrcoef(bat_indexSO,rank_total_k['PCT'])
np.corrcoef(bat_indexSH,rank_total_k['PCT'])
np.corrcoef(bat_indexSF,rank_total_k['PCT'])
np.corrcoef(bat_indexHBP,rank_total_k['PCT'])
np.corrcoef(bat_indexAVG,rank_total_k['PCT'])
np.corrcoef(bat_indexOBP,rank_total_k['PCT'])
np.corrcoef(bat_indexSLG,rank_total_k['PCT'])
np.corrcoef(bat_indexOPS,rank_total_k['PCT'])

array([[1.        , 0.31315581],
       [0.31315581, 1.        ]])

In [0]:
bat_total

Year            Player Team Pos    G   AB    R   TH    H  2B  ...  CS  \
0    2010     Ichiro Suzuki  SEA  OF  162  680   74  214  175  30  ...   9   
1    2010       Derek Jeter  NYY  SS  157  663  111  179  136  30  ...   5   
2    2010     Michael Young  TEX  3B  157  656   99  186  126  36  ...   2   
3    2010       Juan Pierre  CWS  OF  160  651   96  179  157  18  ...  18   
4    2010      Rickie Weeks  MIL  DH  160  651  112  175  110  32  ...   4   
..    ...               ...  ...  ..  ...  ...  ...  ...  ...  ..  ...  ..   
688  2019       Jose Rondon  BAL  2B    1    1    0    0    0   0  ...   0   
689  2019   Travis d'Arnaud  LAD   C    1    1    0    0    0   0  ...   0   
690  2019     Aaron Altherr   SF  OF    1    1    0    0    0   0  ...   0   
691  2019       Rob Brantly  PHI   C    1    1    0    0    0   0  ...   0   
692  2019  John Ryan Murphy  ATL   C    1    1    0    0    0   0  ...   0   

     BB   SO  SH  SF  HBP    AVG    OBP    SLG    OPS  
0    45   86   3   1    3  0.315  0.359  0.394  0.753  
1    63  106   1   3    9  0.270  0.340  0.370  0.710  
2    50  115   0  11    1  0.284  0.330  0.444  0.774  
3    45   47  15   2   21  0.275  0.341  0.316  0.657  
4    76  184   0   2   25  0.269  0.366  0.464  0.830  
..   ..  ...  ..  ..  ...    ...    ...    ...    ...  
688   0    0   0   0    0  0.000  0.000  0.000  0.000  
689   0    0   0   0    0  0.000  0.000  0.000  0.000  
690   0    1   0   0    0  0.000  0.000  0.000  0.000  
691   0    1   0   0    0  0.000  0.000  0.000  0.000  
692   0    0   0   0    0  0.000  0.000  0.000  0.000  

[6848 rows x 24 columns]

In [0]:
bat_total=bat_total[['Year','Player', 'Team', 'Pos', 'G', 'AB', 'R', 'TH', 'H', '2B', '3B', 'HR',
       'RBI', 'SB', 'CS', 'BB', 'SO', 'SH', 'SF', 'HBP', 'AVG', 'OBP', 'SLG','OPS']]

In [0]:
bat_total.to_csv('../Data/MLB_data_edit/bat_total.csv')

In [0]:
from sklearn import preprocessing

In [0]:
# col이라는 변수에 각 컬럼명의 내용을 담음


R = bat_total.groupby(by=['Year','Team']).R.mean()
TH = bat_total.groupby(by=['Year','Team']).TH.mean()
H= bat_total.groupby(by=['Year','Team']).H.mean()
B2= bat_total.groupby(by=['Year','Team']).2B.mean()
B3= bat_total.groupby(by=['Year','Team']).3B.mean()
HR= bat_totall.groupby(by=['Year','Team']).HR.mean()
RBI= bat_total.groupby(by=['Year','Team']).RBI.mean()
SB= bat_total.groupby(by=['Year','Team']).SB.mean()
CS =  bat_total.groupby(by=['Year','Team']).CS.mean()
BB =  bat_total.groupby(by=['Year','Team']).BB.mean()
SO =  bat_total.groupby(by=['Year','Team']).SO.mean()
SH =  bat_total.groupby(by=['Year','Team']).SH.mean()
SF =  bat_total.groupby(by=['Year','Team']).SF.mean()
HBP =  bat_total.groupby(by=['Year','Team']).HBP.mean()
AVG =  bat_total.groupby(by=['Year','Team']).AVG.mean()
OBP =  bat_total.groupby(by=['Year','Team']).OBP.mean()
SLG =  bat_total.groupby(by=['Year','Team']).SLG.mean()
OPS =  bat_total.groupby(by=['Year','Team']).OPS.mean()
PCT = rank_total.sort_values(by=['Year','Team']) # 승률



SyntaxError: invalid syntax (<ipython-input-81-f1df3f40567f>, line 7)

In [0]:
bat_df = pd.DataFrame(index=['R', 'TH', 'H', '2B', '3B', 'HR','RBI','SB','CS','BB','SO','SH','SF','HBP','AVG','OBP','SLG','OPS'],columns={'PCT':0})

In [0]:
bat_df

In [0]:

"""
R = bat_total.groupby(by=['Year','Team']).R.mean()
TH = bat_total.groupby(by=['Year','Team']).TH.mean()
H= bat_total.groupby(by=['Year','Team']).H.mean()
2B= bat_total.groupby(by=['Year','Team'])['2B'].mean()
3B= bat_total.groupby(by=['Year','Team'])['3B'].mean()
HR= bat_totall.groupby(by=['Year','Team']).HR.mean()
RBI= bat_total.groupby(by=['Year','Team']).RBI.mean()
SB= bat_total.groupby(by=['Year','Team']).SB.mean()
CS =  bat_total.groupby(by=['Year','Team']).CS.mean()
BB =  bat_total.groupby(by=['Year','Team']).BB.mean()
SO =  bat_total.groupby(by=['Year','Team']).SO.mean()
SH =  bat_total.groupby(by=['Year','Team']).SH.mean()
SF =  bat_total.groupby(by=['Year','Team']).SF.mean()
HBP =  bat_total.groupby(by=['Year','Team']).HBP.mean()
AVG =  bat_total.groupby(by=['Year','Team']).AVG.mean()
OBP =  bat_total.groupby(by=['Year','Team']).OBP.mean()
SLG =  bat_total.groupby(by=['Year','Team']).SLG.mean()
OPS =  bat_total.groupby(by=['Year','Team']).OPS.mean()
PCT = rank_total.sort_values(by=['Year','Team'])
"""


bat_df1 = pd.DataFrame({'R':bat_total.groupby(by=['Year','Team']).R.mean().values,
                        'TH':bat_total.groupby(by=['Year','Team']).TH.mean().values,
                        'H':bat_total.groupby(by=['Year','Team']).H.mean().values,
                        '2B':bat_total.groupby(by=['Year','Team'])['2B'].mean().values,
                        '3B':bat_total.groupby(by=['Year','Team'])['3B'].mean().values,
                        'HR':bat_total.groupby(by=['Year','Team']).HR.mean().values,
                        'RBI':bat_total.groupby(by=['Year','Team']).RBI.mean().values,
                        'SB':bat_total.groupby(by=['Year','Team']).SB.mean().values,
                        'CS':bat_total.groupby(by=['Year','Team']).CS.mean().values,
                        'BB':bat_total.groupby(by=['Year','Team']).BB.mean().values,
                        'SO':bat_total.groupby(by=['Year','Team']).SO.mean().values,
                        'SH':bat_total.groupby(by=['Year','Team']).SH.mean().values,
                        'SF':bat_total.groupby(by=['Year','Team']).SF.mean().values,
                        'HBP':bat_total.groupby(by=['Year','Team']).HBP.mean().values,
                        'AVG':bat_total.groupby(by=['Year','Team']).AVG.mean().values,
                        'OBP':bat_total.groupby(by=['Year','Team']).OBP.mean().values,
                        'SLG':bat_total.groupby(by=['Year','Team']).SLG.mean().values,
                        'OPS':bat_total.groupby(by=['Year','Team']).OPS.mean().values                       
                })

bat_df1.head()

R         TH          H         2B        3B        HR        RBI  \
0  34.400000  65.350000  40.200000  14.550000  1.700000  8.900000  33.250000   
1  33.333333  63.952381  42.238095  14.047619  1.142857  6.523810  32.095238   
2  27.863636  65.409091  46.409091  12.000000  0.954545  6.045455  26.227273   
3  27.233333  50.200000  30.533333  11.900000  0.733333  7.033333  26.000000   
4  31.952381  65.428571  43.142857  13.952381  1.285714  7.047619  30.428571   

         SB        CS         BB         SO        SH        SF       HBP  \
0  4.250000  2.050000  28.750000  70.300000  0.800000  1.900000  1.850000   
1  2.904762  1.333333  28.428571  46.714286  1.523810  1.619048  2.285714   
2  3.454545  1.545455  19.227273  47.636364  1.409091  2.045455  2.454545   
3  2.266667  0.566667  19.500000  37.833333  0.800000  1.500000  1.566667   
4  2.619048  1.476190  22.190476  52.904762  0.761905  1.761905  2.333333   

        AVG       OBP       SLG       OPS  
0  0.234700  0.308250  0.380750  0.689000  
1  0.227238  0.346238  0.377143  0.723381  
2  0.237455  0.285273  0.345000  0.630273  
3  0.212200  0.274267  0.347033  0.621300  
4  0.252381  0.322190  0.380048  0.702238

In [0]:
rank_total.reset_index(inplace=True)

In [0]:
del rank_total['index']

In [0]:
rank_total.head()

Team   W   L    PCT GB   HOME   AWAY   RS   RA  DIFF  Year
0  PHI  97  65  0.599  -  54-30  43-35  772  640   132  2010
1   TB  96  66  0.593  1  49-32  47-34  802  649   153  2010
2  NYY  95  67  0.586  2  52-29  43-38  859  693   166  2010
3  MIN  94  68  0.580  3  53-28  41-40  781  671   110  2010
4   SF  92  70  0.568  5  49-32  43-38  697  583   114  2010

In [0]:
bat_df1.reset_index(inplace=True)

In [0]:
del bat_df1['index']

In [0]:
bat_df1.head()

R         TH          H         2B        3B        HR        RBI  \
0  34.400000  65.350000  40.200000  14.550000  1.700000  8.900000  33.250000   
1  33.333333  63.952381  42.238095  14.047619  1.142857  6.523810  32.095238   
2  27.863636  65.409091  46.409091  12.000000  0.954545  6.045455  26.227273   
3  27.233333  50.200000  30.533333  11.900000  0.733333  7.033333  26.000000   
4  31.952381  65.428571  43.142857  13.952381  1.285714  7.047619  30.428571   

         SB        CS         BB         SO        SH        SF       HBP  \
0  4.250000  2.050000  28.750000  70.300000  0.800000  1.900000  1.850000   
1  2.904762  1.333333  28.428571  46.714286  1.523810  1.619048  2.285714   
2  3.454545  1.545455  19.227273  47.636364  1.409091  2.045455  2.454545   
3  2.266667  0.566667  19.500000  37.833333  0.800000  1.500000  1.566667   
4  2.619048  1.476190  22.190476  52.904762  0.761905  1.761905  2.333333   

        AVG       OBP       SLG       OPS  
0  0.234700  0.308250  0.380750  0.689000  
1  0.227238  0.346238  0.377143  0.723381  
2  0.237455  0.285273  0.345000  0.630273  
3  0.212200  0.274267  0.347033  0.621300  
4  0.252381  0.322190  0.380048  0.702238

In [0]:
bat_df1["PCT"]=rank_total["PCT"]

In [0]:
bat_df1

R         TH          H         2B        3B         HR  \
0    34.400000  65.350000  40.200000  14.550000  1.700000   8.900000   
1    33.333333  63.952381  42.238095  14.047619  1.142857   6.523810   
2    27.863636  65.409091  46.409091  12.000000  0.954545   6.045455   
3    27.233333  50.200000  30.533333  11.900000  0.733333   7.033333   
4    31.952381  65.428571  43.142857  13.952381  1.285714   7.047619   
..         ...        ...        ...        ...       ...        ...   
295  35.619048  61.809524  39.333333  11.333333  1.142857  10.000000   
296  29.500000  54.769231  34.153846  11.192308  1.115385   8.307692   
297  42.631579  72.263158  43.684211  15.578947  1.263158  11.736842   
298  30.166667  54.041667  31.625000  11.250000  0.875000  10.291667   
299  40.619048  67.571429  41.238095  14.095238  1.285714  10.952381   

           RBI        SB        CS         BB         SO        SH        SF  \
0    33.250000  4.250000  2.050000  28.750000  70.300000  0.800000  1.900000   
1    32.095238  2.904762  1.333333  28.428571  46.714286  1.523810  1.619048   
2    26.227273  3.454545  1.545455  19.227273  47.636364  1.409091  2.045455   
3    26.000000  2.266667  0.566667  19.500000  37.833333  0.800000  1.500000   
4    30.428571  2.619048  1.476190  22.190476  52.904762  0.761905  1.761905   
..         ...       ...       ...        ...        ...       ...       ...   
295  33.380952  5.476190  1.333333  26.428571  61.714286  0.428571  1.761905   
296  28.000000  3.615385  1.423077  20.807692  56.961538  0.307692  1.307692   
297  40.263158  6.894737  2.000000  28.000000  82.315789  0.842105  2.315789   
298  29.041667  2.125000  0.833333  21.166667  62.666667  0.583333  1.166667   
299  38.380952  5.428571  1.380952  27.380952  55.857143  0.904762  2.000000   

          HBP       AVG       OBP       SLG       OPS    PCT  
0    1.850000  0.234700  0.308250  0.380750  0.689000  0.599  
1    2.285714  0.227238  0.346238  0.377143  0.723381  0.593  
2    2.454545  0.237455  0.285273  0.345000  0.630273  0.586  
3    1.566667  0.212200  0.274267  0.347033  0.621300  0.580  
4    2.333333  0.252381  0.322190  0.380048  0.702238  0.568  
..        ...       ...       ...       ...       ...    ...  
295  3.571429  0.233810  0.304381  0.388571  0.692952  0.414  
296  2.807692  0.236462  0.293769  0.393846  0.687615  0.364  
297  3.526316  0.237842  0.306947  0.410684  0.717632  0.352  
298  1.875000  0.207583  0.266583  0.364167  0.630750  0.333  
299  3.857143  0.239952  0.305714  0.392952  0.698667  0.292  

[300 rows x 19 columns]

In [0]:
bat_df1.to_csv('../Data/MLB_data_edit/b_total_no_scale.csv')

In [0]:
# 표준화 작업
col = ['R', 'TH', 'H', '2B', '3B', 'HR','RBI','SB','CS','BB','SO','SH','SF','HBP','AVG','OBP','SLG','OPS','PCT']
x=bat_df1[col].values
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)

In [0]:
x_scaled

In [0]:
bat_scaled = pd.DataFrame(x_scaled, columns=col, index=bat_df1.index)

In [0]:
bat_scaled

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline


In [0]:
# 상관계수 구하자
col = ['R', 'TH', 'H', '2B', '3B', 'HR','RBI','SB','CS','BB','SO','SH','SF','HBP','AVG','OBP','SLG','OPS']
R=np.corrcoef(bat_scaled['R'],bat_scaled['PCT'])
TH=np.corrcoef(bat_scaled['TH'],bat_scaled['PCT'])
H=np.corrcoef(bat_scaled['H'],bat_scaled['PCT'])
B2=np.corrcoef(bat_scaled['2B'],bat_scaled['PCT'])
B3=np.corrcoef(bat_scaled['3B'],bat_scaled['PCT'])
HR=np.corrcoef(bat_scaled['HR'],bat_scaled['PCT'])
RBI=np.corrcoef(bat_scaled['RBI'],bat_scaled['PCT'])
SB=np.corrcoef(bat_scaled['SB'],bat_scaled['PCT'])
CS=np.corrcoef(bat_scaled['CS'],bat_scaled['PCT'])
BB=np.corrcoef(bat_scaled['BB'],bat_scaled['PCT'])
SO=np.corrcoef(bat_scaled['SO'],bat_scaled['PCT'])
SH=np.corrcoef(bat_scaled['SH'],bat_scaled['PCT'])
SF=np.corrcoef(bat_scaled['SF'],bat_scaled['PCT'])
HBP=np.corrcoef(bat_scaled['HBP'],bat_scaled['PCT'])
AVG=np.corrcoef(bat_scaled['AVG'],bat_scaled['PCT'])
OBP=np.corrcoef(bat_scaled['OBP'],bat_scaled['PCT'])
SLG=np.corrcoef(bat_scaled['SLG'],bat_scaled['PCT'])
OPS=np.corrcoef(bat_scaled['OPS'],bat_scaled['PCT'])

In [0]:
hitmap = pd.DataFrame({
    'R':R[1][0],
    'TH':TH[1][0],
    'H':H[1][0],
    '2B':B2[1][0],
    '3B':B3[1][0],
    'HR':HR[1][0],
    'RBI':RBI[1][0],
    'SB':SB[1][0],
    'CS':CS[1][0],
    'BB':BB[1][0],
    'SO':SO[1][0],
    'SH':SH[1][0],
    'SF':SF[1][0],
    'HBP':HBP[1][0],
    'AVG':AVG[1][0],
    'OBP':OBP[1][0],
    'SLG':SLG[1][0],
    'OPS':OPS[1][0],
    
},index=['corrcoef'])

In [0]:
hitmap=np.abs(hitmap)

In [0]:
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [0]:
plt.figure(figsize=(5,15))
sns.heatmap(hitmap[col].T,annot=True, fmt='f', linewidths=1, cmap='RdPu')
plt.title('corrcoef of Batter')
plt.show()

In [0]:

x = bat_total[col].values
# min_max_scaler이라는 변수에 min,max값을 계산해주는 것을 담고
# 그 최대 최소 값을 이용해 단위를 줄여줌
min_max_scaler = preprocessing.MinMaxScaler()
# x_sacled 새로운 변수에 x를 넣어서 실행
x_sacled = min_max_scaler.fit_transform(x)

In [0]:
import matplotlib.pyplot as plt
import missingno as msng
msng.matrix(bat_10)

In [0]:
bat_10 = pd.read_csv('../Data/MLB_data_edit/2019_bat.csv')

In [0]:
bat_10.head()

In [0]:
bat_10.drop['Unnamed']

In [0]:
bat_10 =  bat_10[['Player', 'Team', 'Pos', 'G', 'AB', 'R', 'TH','H', '2B', '3B', 'HR', 'RBI',
       'SB', 'CS', 'BB', 'SO', 'SH', 'SF', 'HBP', 'AVG', 'OBP', 'SLG', 'OPS']]

In [0]:
bat_10.head()

In [0]:
# 수정본 저장
bat_10.to_csv('../Data/MLB_data/2019_bat.csv')

In [0]:
def save(x):
    del x['Age']
    x.rename(columns={"H":"TH"}, inplace=True)
    x['H']=x['TH']-(x['2B']+x['3B']+x['HR'])
    x=x[['Player', 'Team', 'Pos', 'G', 'AB', 'R', 'TH', 'H','2B', '3B', 'HR', 'RBI','SB', 'CS', 'BB', 'SO', 'SH', 'SF', 'HBP', 'AVG', 'OBP', 'SLG', 'OPS']]

In [0]:
b_corr.corrcoef_

NameError: name 'b_corr' is not defined

In [0]:
import pandas as pd
import numpy as np 